

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TantXHX (https://sketchfab.com/tantxhx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/himtheone-day-and-night-272fcc8c0fb3492e9f7c6e83a817e1fe
Title: Him/TheOne (Day and Night)
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useMotionValue, useSpring } from 'motion/react'
import { useFrame } from '@react-three/fiber'


export function Wizard(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/himtheone_day_and_night.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (animations.length > 0 ) {
        actions[animations[0].name]?.play();
    }
  }, [actions, animations])


    const yPosition = useMotionValue(5);
    const ySpring = useSpring(yPosition, {damping: 30})

    useEffect(() => {
        ySpring.set(-1);
    }, [ySpring])
        
    useFrame(() => {
        group.current.position.y = ySpring.get();
    })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.00433}>
          <group name="e9df6537e15349808781771e3514ec64fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="exproted">
                  <group name="Object_5">
                    {/* EL ESQUELETO */}
                    <primitive object={nodes._rootJoint} />
                    
                    {/* LAS MALLAS DEL CUERPO (SKINNED MESHES) */}
                    <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Mask} skeleton={nodes.Object_8.skeleton} />
                    <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Eye_Main} skeleton={nodes.Object_10.skeleton} />
                    <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.material} skeleton={nodes.Object_12.skeleton} />
                    <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Body} skeleton={nodes.Object_14.skeleton} />
                    <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Cloth} skeleton={nodes.Object_16.skeleton} />
                    <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Deco} skeleton={nodes.Object_18.skeleton} />
                    <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Cloth} skeleton={nodes.Object_20.skeleton} />
                    <skinnedMesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Pants} skeleton={nodes.Object_22.skeleton} />
                    <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.Deco_Foot} skeleton={nodes.Object_24.skeleton} />
                    <skinnedMesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.Cloak_Up} skeleton={nodes.Object_26.skeleton} />
                    <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Cloak} skeleton={nodes.Object_28.skeleton} />
                    
                    {/* He quitado sky_ball, stars, vfx y energy_ball */}
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/himtheone_day_and_night.glb')
